### PR TITLE
Make py27 great again

### PR DESCRIPTION
**Pull request by menshikh-iv**
Related https://github.com/RaRe-Technologies/gensim/pull/2812/

### CODE REVIEW

**Comment by mpenkov** [comment]
@piskvorky Looks like appveyor is not picking up this PR. This is similar to what was happening with smart_open not too long ago. Can you please repeat the same procedure?

https://github.com/RaRe-Technologies/smart_open/pull/479#issuecomment-617504414

**Comment by piskvorky** [comment]
@mpenkov done: revoked & imported.

This is a different repo though (MacPython), not sure how that's connected.

**Comment by menshikh-iv** [comment]
Hi @matthew-brett, can you help us with appveyor (this don't trigger), @piskvorky revoked & imported them, I re-create webhook, but this doesn't help.

**Comment by mpenkov** [comment]
@piskvorky @menshikh-iv If we don't hear from @matthew-brett today, I propose we fork this repo under RaRe-Technologies so we can build the wheels over the weekend. Thoughts?

**Comment by menshikh-iv** [comment]
@mpenkov okay
@piskvorky don't forget to give @mpenkov and me max permissions in the fork (`RaRe-Technologies/gensim-wheels`)

**Comment by piskvorky** [comment]
Sure. I don't really understand the problem here and didn't look into `gensim-wheels` at all, but I can fork this repo. That shouldn't be a problem.

Why wasn't it under `RARE-Technologies` to start with?

**Comment by menshikh-iv** [comment]
> Why wasn't it under RARE-Technologies to start with?

Idk, better to ask @tmylk

**Comment by piskvorky** [comment]
`gensim-wheels` mirrored to https://github.com/RaRe-Technologies/gensim-wheels

**Comment by matthew-brett** [comment]
Sorry - I missed the ping - but yes, forking is the right way to go - I find it's often tricky to get Appveyor permissions working well.

Do you want me to transfer the repo somewhere?

**Comment by menshikh-iv** [comment]
@matthew-brett no, thanks, @piskvorky  already did that :)

**Pull request closed without merging**
