### PR TITLE
Fix building wheels on OSX

### PR DESCRIPTION
**Pull request by menshikh-iv**
https://github.com/RaRe-Technologies/gensim/issues/2794

### CODE REVIEW

**Review by mpenkov — APPROVED** [review]

**Comment by piskvorky** [comment]
@menshikh-iv thanks – is there a TL;DR version of what was wrong?

**Comment by menshikh-iv** [comment]
@piskvorky 

### Hidden fails 1

The story starts from https://github.com/MacPython/gensim-wheels/commit/1009a3f2fbc37ede7516e37bc5edcdd7529beb47, 1 year ago this was needed for release wheels (CI doesn't give them if tests failed) and this was reverted only several days ago (when I dug into CI logs and found this).

For this reason, some of the wheels can be broken, because we don't track test fails.

How this works now:
- test fail -> CI job fail
- wheels produced in any case (no matter, is tests failed or not), to avoid `|| true` situation in the future.

### Hidden fails 2

According to the changes above, I created https://github.com/RaRe-Technologies/gensim/pull/2791 to fix some of them & checking build. So, this partially helps (at least with our tests), but doesn't fix all. Others wired problem (especially with OSX) still persist here.

### Travis updates

From start, wheels for osx was broken, I'm using https://github.com/RaRe-Technologies/gensim/issues/2794 as indicator + carefully read logs (we have a batch of wired exceptions here)


- Travis update CI file directives, so, I updated them according to modern guidelines
- OSX VMs changed, this was the main reason for "broken osx wheels". I investigated, how this works in `numpy` and `scikit-learn`  wheels and apply these approaches to the current repo.

**Comment by piskvorky** [comment]
Thanks.

> From start, wheels for osx was broken

How do you mean? Many OSX wheels worked, when I tested [here](https://github.com/RaRe-Technologies/gensim/issues/2794#issuecomment-613894566).

**Comment by menshikh-iv** [comment]
> How do you mean?

When I start working on this PR, OSX can build only 3.5 wheels (with batch of failed tests after, but it doesn't matter), 3.6 and 3.7 doesn't produce a wheel at all (broken on compilation stage with wired errors)

**Pull request merged**
